media:
  input: assets/images
  output: /assets/images
  categories:
    - image
  rename: safe

content:
    - name: partner
    label: Affiliate Settings
    type: file
    path: assets/partner-config.js
    format: code
    operations:
      delete: false

  - name: styles
    label: Website Style & Fonts
    type: file
    path: assets/styles.css
    format: code

  - name: pages
    label: Website Pages
    type: collection
    path:.
    filename: "{primary}.html"
    view:
      fields:
        - name
    fields:
      - name: body
        label: Page Content
        type: code