const AFFILIATE_CONFIG={bookingAid:"",bookingLabel:"",bookingBaseUrl:"https://www.booking.com/searchresults.html"};
const qs=(s)=>document.querySelector(s),qsa=(s)=>[...document.querySelectorAll(s)];
const menu=qs('.menu-toggle'),nav=qs('.main-nav');if(menu){menu.addEventListener('click',()=>{nav.classList.toggle('open');menu.setAttribute('aria-expanded',nav.classList.contains('open'))})}
let activeTab='hotels';qsa('.search-tabs button').forEach(btn=>btn.addEventListener('click',()=>{qsa('.search-tabs button').forEach(b=>b.classList.remove('active'));btn.classList.add('active');activeTab=btn.dataset.tab;qs('#searchNote').textContent=activeTab==='hotels'?'Hotel searches open with our booking partner. Affiliate tracking will be activated after partner approval.':`${btn.textContent} integration is ready for an approved partner. For now, submit an enquiry or use the curated sections below.`}));
function bookingUrl(destination,checkin='',checkout='',guests='2'){
 const url=new URL(AFFILIATE_CONFIG.bookingBaseUrl);url.searchParams.set('ss',destination||'Bali');if(checkin)url.searchParams.set('checkin',checkin);if(checkout)url.searchParams.set('checkout',checkout);url.searchParams.set('group_adults',guests);url.searchParams.set('no_rooms','1');url.searchParams.set('group_children','0');if(AFFILIATE_CONFIG.bookingAid)url.searchParams.set('aid',AFFILIATE_CONFIG.bookingAid);if(AFFILIATE_CONFIG.bookingLabel)url.searchParams.set('label',AFFILIATE_CONFIG.bookingLabel);return url.toString();
}
qs('#travelSearch')?.addEventListener('submit',e=>{e.preventDefault();const d=qs('#destination').value,ci=qs('#checkin').value,co=qs('#checkout').value,g=qs('#guests').value;if(activeTab==='hotels'){window.open(bookingUrl(d,ci,co,g),'_blank','noopener')}else{location.href='#contact'}});
qsa('.hotel-book').forEach(b=>b.addEventListener('click',()=>window.open(bookingUrl(b.dataset.destination),'_blank','noopener')));
qs('[data-language]')?.addEventListener('click',()=>{const fa=document.documentElement.lang==='fa';document.documentElement.lang=fa?'en':'fa';document.documentElement.dir=fa?'ltr':'rtl';localStorage.setItem('benarian-language',fa?'en':'fa');alert(fa?'English layout restored. Full Persian content will be expanded in the next content release.':'چیدمان فارسی فعال شد. ترجمه کامل محتوا در نسخه محتوایی بعدی تکمیل می‌شود.');});
const savedLang=localStorage.getItem('benarian-language');if(savedLang==='fa'){document.documentElement.lang='fa';document.documentElement.dir='rtl'}
